version: "3"
## Service Definitions
services:

  ## Klippy Services
  ##
  klipper-1:
    image: mkuf/klipper:latest
    restart: unless-stopped
    privileged: true
    logging:
      driver: none
    depends_on:
      init-1:
        condition: service_completed_successfully
      socat-1:
        condition: service_started
    command: -I printer_data/run/klipper-1.tty -a printer_data/run/klipper-1.sock printer_data/config/printer-1.cfg -l printer_data/logs/klippy-1.log
    volumes:
      - /dev:/dev
      - ./config-1:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
    labels:
      org.prind.service: klipper-1

  klipper-2:
    image: mkuf/klipper:latest
    restart: unless-stopped
    privileged: true
    logging:
      driver: none
    depends_on:
      init-2:
        condition: service_completed_successfully
      socat-2:
        condition: service_started
    command: -I printer_data/run/klipper-2.tty -a printer_data/run/klipper-2.sock printer_data/config/printer-2.cfg -l printer_data/logs/klippy-2.log
    volumes:
      - /dev:/dev
      - ./config-2:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
    labels:
      org.prind.service: klipper-2


  ## WebApi
  ##
  moonraker-1:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    depends_on:
      init-1:
        condition: service_completed_successfully
      klipper-1:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ./config-1:/opt/printer_data/config
    profiles:
      - fluidd
      - mainsail
      - klipperscreen
      - moonraker-telegram-bot
      - mobileraker_companion
    labels:
      org.prind.service: moonraker-1
      traefik.enable: true
      traefik.http.services.moonraker-1.loadbalancer.server.port: 7125
      traefik.http.routers.moonraker-1.rule: PathPrefix(`/websocket`,`/printer`,`/api`,`/access`,`/machine`,`/server`)
      traefik.http.routers.moonraker-1.entrypoints: web

  moonraker-2:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    depends_on:
      init-2:
        condition: service_completed_successfully
      klipper-2:
        condition: service_started
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ./config-2:/opt/printer_data/config
    profiles:
      - fluidd
      - mainsail
      - klipperscreen
      - moonraker-telegram-bot
      - mobileraker_companion
    labels:
      org.prind.service: moonraker-2
      traefik.enable: true
      traefik.http.services.moonraker-2.loadbalancer.server.port: 7126
      traefik.http.routers.moonraker-2.rule: PathPrefix(`/websocket`,`/printer`,`/api`,`/access`,`/machine`,`/server`)
      traefik.http.routers.moonraker-2.entrypoints: web

  ## Frontends
  ##
  octoprint:
    image: octoprint/octoprint:minimal
    restart: unless-stopped
    depends_on:
      klipper:
        condition: service_started
    privileged: true
    volumes:
      - /dev:/dev
      - run:/opt/printer_data/run
      - octoprint:/octoprint
      - ./config/octoprint.yaml:/octoprint/octoprint/config.yaml
    profiles:
      - octoprint
    labels:
      org.prind.service: octoprint
      traefik.enable: true
      traefik.http.services.octoprint.loadbalancer.server.port: 5000
      traefik.http.routers.octoprint.rule: PathPrefix(`/`)
      traefik.http.routers.octoprint.entrypoints: web

  fluidd:
    image: ghcr.io/fluidd-core/fluidd:latest
    restart: unless-stopped
    profiles:
      - fluidd
    labels:
      org.prind.service: fluidd
      traefik.enable: true
      traefik.http.services.fluidd.loadbalancer.server.port: 80
      traefik.http.routers.fluidd.rule: PathPrefix(`/`)
      traefik.http.routers.fluidd.entrypoints: web

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:edge
    restart: unless-stopped
    profiles:
      - mainsail
    labels:
      org.prind.service: mainsail
      traefik.enable: true
      traefik.http.services.mainsail.loadbalancer.server.port: 80
      traefik.http.routers.mainsail.rule: PathPrefix(`/`)
      traefik.http.routers.mainsail.entrypoints: web

  ## additional Services
  ##
  klipperscreen:
    image: mkuf/klipperscreen:latest
    restart: unless-stopped
    network_mode: host
    pid: host
    profiles:
      - klipperscreen
    volumes:
      - /run/systemd:/run/systemd
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./config:/opt/cfg
    labels:
      org.prind.service: klipperscreen

  moonraker-telegram-bot:
    image: lefskiy/moonraker-telegram-bot:latest
    restart: unless-stopped
    logging:
      driver: none
    profiles:
      - moonraker-telegram-bot
    volumes:
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - ./config:/opt/printer_data/config
    labels:
      org.prind.service: moonraker-telegram-bot

  mobileraker_companion:
    image: ghcr.io/clon1998/mobileraker_companion:latest
    restart: unless-stopped
    profiles:
      - mobileraker_companion
    volumes:
      - ./config:/opt/printer_data/config
    labels:
      org.prind.service: mobileraker_companion

  hostmcu:
    image: mkuf/klipper:latest-hostmcu
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev:/dev
      - run:/opt/printer_data/run
    profiles:
      - hostmcu
    labels:
      org.prind.service: hostmcu

  ## Accompanying Services/Infra
  ##

  ## Config dir needs to be writable by uid/gid 1000
  ## This container sets the right permissions and exits
  init-1:
    image: busybox:latest
    command: chown -R 1000:1000 /prind/config-1
    volumes:
      - .:/prind
    labels:
      org.prind.service: init-1

  init-2:
    image: busybox:latest
    command: chown -R 1000:1000 /prind/config-2
    volumes:
      - .:/prind
    labels:
      org.prind.service: init-2

  ## Loadbalancer/Proxy
  traefik:
    image: traefik:v2.5
    command:
      - "--accesslog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      org.prind.service: traefik

  socat-1:
    image: alpine/socat:1.7.4.4
    privileged: true
    container_name: socat-1
    command: "-d -d -d -x pty,link=/dev/virtualcom0,raw,group-late=dialout,mode=660,ixon=1,ixoff=1,parenb=1,parodd=1,cstopb=1,cs8 tcp:10.0.1.7:23"
    #command: "pty,link=/opt/printer,raw,b230400,cstopb=1,cs8,group-late=dialout,mode=777 tcp:192.168.0.7:23"
    #command: "-d -d -d -x PTY,raw,b230400,parenb=0,cstopb=2,cs8,link=/opt/printer,group-late=dialout,mode=660 tcp:192.168.0.7:23"
    volumes:
      - "/dev:/dev"
    restart: unless-stopped
    profiles:
      - socat
    labels:
      org.prind.service: socat-1

  socat-2:
    image: alpine/socat:1.7.4.4
    privileged: true
    container_name: socat-2
    command: "-d -d -d -x pty,link=/dev/virtualcom1,raw,group-late=dialout,mode=660,ixon=1,ixoff=1,parenb=1,parodd=1,cstopb=1,cs8 tcp:10.0.1.8:23"
    #command: "pty,link=/opt/printer,raw,b230400,cstopb=1,cs8,group-late=dialout,mode=777 tcp:192.168.0.7:23"
    #command: "-d -d -d -x PTY,raw,b230400,parenb=0,cstopb=2,cs8,link=/opt/printer,group-late=dialout,mode=660 tcp:192.168.0.7:23"
    volumes:
      - "/dev:/dev"
    restart: unless-stopped
    profiles:
      - socat
    labels:
      org.prind.service: socat-2

volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  dev:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  octoprint:
  moonraker-db:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
